Repository Andy-J-B/ClearWrite, pull requests merged in 2024-11, with the labels that each got.

#13 EvalPage into TextGears
  client/src/App.jsx
  client/src/components/evaluationPage.jsx
  client/src/components/textGearsData.json
  server/responses/textGears.txt
  server/routers/textGears.js
Labels: enhancement, Week 2

#14 Merge testing-textgears to TextGears
  package-lock.json
  package.json
  server/controller/textGearsController.js
  server/package.json
  server/routers/textGears.js
  server/test/textGearsController.test.js
Labels: documentation, enhancement, Week 2

#15 Merge TextGears
  client/src/App.jsx
  client/src/components/evaluationPage.jsx
  client/src/components/mainPage.jsx
  client/src/components/textGearsData.json
  package-lock.json
  package.json
  server/controller/textGearsController.js
  server/index.js
  server/package-lock.json
  server/package.json
  server/responses/textGears.txt
  server/routers/textGears.js
  server/test/textGearsController.test.js
Labels: enhancement, Week 2

#31 Sapling into Routers
  package-lock.json
  package.json
  server/index.js
  server/package-lock.json
  server/package.json
  server/responses/sapling.txt
  server/routers/sapling.js
  server/test/sapling.test.js
Labels: Week 2

#32 Loading sc
  client/package-lock.json
  client/package.json
  client/src/AboutPage.jsx
  client/src/App.jsx
  client/src/HomePage.jsx
  client/src/Homepage.css
  client/src/LoadingPage.jsx
  client/src/image/clearwrite-background.png
Labels: enhancement

#42 Add intro page
  client/src/App.jsx
  client/src/assets/images/introBackground.jpg
  client/src/components/IntroPage.jsx
  client/src/css/IntroPage.css
Labels: enhancement, Week 3
